apps/core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import index, home, comocomprar, galeria, contato, eventos,detail_eventos,detail_colecoes,detail_galeria

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^home/$', home, name='home'),
	url(r'^galeria/$', galeria, name='all-galeria'),
	url(r'^contato/$', contato, name='contato'),
	url(r'^eventos/$', eventos, name='all-eventos'),
	url(r'^comocomprar/$', comocomprar, name='comocomprar'),
	url(r'^colecoes/(?P<slug>[\w-]+)/$', detail_colecoes, name='detail-colecoes'),
	url(r'^galeria/(?P<slug>[\w-]+)/$', detail_galeria, name='detail-galeria'),
	url(r'^eventos/(?P<slug>[\w-]+)/$', detail_eventos, name='detail-eventos'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

georginanogueira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.core import urls as core_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(core_urls, namespace='core')),
]

apps/core/models.py
from django.db import models
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User
from django.core.validators   import MaxValueValidator,MinValueValidator,MinLengthValidator
from django.template.defaultfilters import slugify


import os.path
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile 
from django.core.files.uploadedfile import SimpleUploadedFile

class Images(models.Model):
    def image_path(self, filename):
        return 'images/{}/'.format(filename)

    def image_thumb_path(self, filename):
        return 'thumbnail/{}/'.format(filename)

    title = models.CharField(max_length=100)
    slug = models.SlugField()
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(upload_to=image_path)
    image_thumbnail = ProcessedImageField(
        upload_to=image_thumb_path,
        processors=[ResizeToFill(319, 200)],
        format='JPEG',
        options={'quality': 80},
        null=True,
        blank=True,
    )

    created_by = models.ForeignKey(User)

    def save_slug(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Images, self).save(*args, **kwargs)

    def create_thumbnail(self):
        image = Image.open(self.image)
        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + '_thumb' + thumb_extension
        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False    # Unrecognized file type
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
             temp_thumb.read())
        self.image_thumbnail.save('%s_thumbnail.%s'%(os.path.splitext(suf.name)[0],FTYPE), suf, save=False)

    def save(self):
        self.create_thumbnail()
        super(Images, self).save()

    class Meta:
        verbose_name = "Imagem"
        verbose_name_plural = "Imagens"

    def __str__(self):
        return self.title

class Colecoes(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    galery = models.ManyToManyField(Images)
    created_by = models.ForeignKey(User)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Colecoes, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Coleção"
        verbose_name_plural = "Coleções"

    def __str__(self):
        return self.title

class ElasUsam(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    galery = models.ManyToManyField(Images)
    created_by = models.ForeignKey(User)
    slug = models.SlugField()
        
    class Meta:
        verbose_name = "Elas Usam"
        verbose_name_plural = "Elas Usam"

    def __str__(self):
        return self.title

class Galeria(models.Model):
    title = models.CharField(max_length=100, unique=True)
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    date = models.DateTimeField(blank=True, null=True)
    galery = models.ManyToManyField(Images)
    created_by = models.ForeignKey(User)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Galeria, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Galeria"
        verbose_name_plural = "Galerias"

    def __str__(self):
        return self.title

class Eventos(models.Model):
    title = models.CharField(max_length=100)
    desc = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    date = models.DateTimeField(blank=True, null=True)
    galery = models.ManyToManyField(Images)
    created_by = models.ForeignKey(User)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Eventos, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.title

class Email(models.Model):
    full_name = models.CharField(max_length=100)
    ddd = models.IntegerField(validators=[MinValueValidator(10, message="Certifique-se que este valor possui 2 digitos."),MaxValueValidator(99)],verbose_name="DDD")
    phone = models.IntegerField(validators=[MaxValueValidator(999999999)],verbose_name='Telefone')
    message = models.TextField()
    send_date = models.DateTimeField(default=timezone.now)
    email = models.EmailField()

    class Meta:
        verbose_name = "Email"
        verbose_name_plural = "Email"

    def __str__(self):
        return self.full_name

apps/core/forms.py
from django import forms
from .models import Email

class EmailForm(forms.ModelForm):
	class Meta:
	    model = Email
	    fields = ['full_name','ddd','phone','message','email',]
	    widgets = {
	        'full_name' : forms.TextInput(attrs={
	            'placeholder':'Nome Compelto',
	            'class':'form-control',
	            'required' : 'required',
	        }),
	        'email' : forms.TextInput(attrs={
	            'placeholder':'Email',
	            'class':'form-control',
	            'required' : 'required',
	        }),
	        'ddd' : forms.TextInput(attrs={
	            'placeholder':'DDD',
	            'class':'form-control',
	            'required' : 'required',
	        }),
	        'phone' : forms.TextInput(attrs={
	            'placeholder':'Telefone',
	            'class':'form-control',
	            'required' : 'required',
	        }),
	        'message' : forms.Textarea(attrs={
	            'placeholder':'Mensagem',
	            'class':'form-control',
	            'required' : 'required',
	        }),
	    }

apps/core/views.py
from django.shortcuts import render
from .models import Images, Eventos, Colecoes, Galeria
from .forms import EmailForm
from django.http import HttpResponse, HttpResponseRedirect


def submenu():
    menu = Colecoes.objects.all()
    return menu

def index(request):
    template_name = 'index.html'
    context = dict(submenu=submenu())
    return render(request,template_name,context)

def home(request):
    template_name = 'home.html'
    context = dict(submenu=submenu())
    return render(request,template_name,context)

def comocomprar(request):
    template_name = 'comocomprar.html'
    context = dict(submenu=submenu())
    return render(request,template_name,context)

def galeria(request):
    template_name = 'galeria/galeria.html'
    rows = Galeria.objects.all()
    context = dict(submenu=submenu(),rows=rows)
    return render(request,template_name,context)

def eventos(request):
    template_name = 'eventos/eventos.html'
    rows = Eventos.objects.all()
    context = dict(submenu=submenu(),rows=rows)
    return render(request,template_name,context)

def detail_eventos(request,slug):
    template_name = 'eventos/detalhe.html'
    rows = Eventos.objects.get(slug=slug)
    context = dict(submenu=submenu(),rows=rows)
    return render(request,template_name,context)

def detail_colecoes(request,slug):
    template_name = 'colecoes/detalhe.html'
    rows = Colecoes.objects.get(slug=slug)
    context = dict(submenu=submenu(),rows=rows)
    return render(request,template_name,context)

def detail_galeria(request,slug):
    template_name = 'galeria/detalhe.html'
    rows = Galeria.objects.get(slug=slug)
    context = dict(submenu=submenu(),rows=rows)
    return render(request,template_name,context)

def contato(request):
    template_name = 'contato/contato.html'
    forms = EmailForm(request.POST)
    if request.method == 'POST':
        if forms.is_valid():
            forms.save()
            return HttpResponseRedirect('/')
    else:
        forms = EmailForm()
    context = dict(submenu=submenu(),forms=forms)
    return render(request,template_name,context)

apps/core/templates/galeria/detalhe.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Portfolio / gallery-->
<section id="portfolio" class="gallery">
  <div class="container clearfix">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-12">
            <h2 class="heading">{% block title %}{{rows.title}}{% endblock %}</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>{{rows.desc}}</p>
          <p>{{rows.date}}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {%for row in rows.galery.all %}
          <div class="col-sm-4">
            <div class="box">
              <a href="{{row.image.url}}" title="" data-toggle="lightbox" data-gallery="portfolio" data-title="{{row.title}}" data-footer="{{row.desc}}">
                <img src="{{row.image_thumbnail.url}}" alt="" class="img-responsive">
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Portfolio / gallery end-->
{% endblock %}

apps/core/templates/galeria/galeria.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Portfolio / gallery-->
<section id="portfolio" class="gallery">
  <div class="container clearfix">
    <div class="row">
      <div class="col-md-12">
        <h2 class="heading">{% block title %}Galeria{% endblock %}</h2>
      </div>
    </div>
    <div class="row">
      {%for row in rows %}
      <div class="thumbnail col-xs-6 col-sm-4 col-lg-12">
        <div class="col-xs-6 col-sm-4 col-lg-6">
          {% with row.galery.all|first as first_image %}
          <a href="{% url 'core:detail-galeria' slug=row.slug %}"><img src="{{first_image.image.url}}" alt="" class="img-responsive"></a>
          {% endwith %}
        </div>
        <div class="col-xs-6 col-sm-4 col-lg-6">
          <div class="caption">
            <h3><a href="{% url 'core:detail-galeria' slug=row.slug %}">{{row.title}}</a></h3>
            <p class="flex-text text-muted">{{row.desc}}</p>
            <p><a class="btn btn-primary" href="{% url 'core:detail-galeria' slug=row.slug %}">{{row.date|date:"Y"}}</a></p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- Portfolio / gallery end-->
{% endblock %}

apps/core/templates/galeria/galeria2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Portfolio / gallery-->
<section id="portfolio" class="gallery">
  <div class="container clearfix">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <h2 class="heading">{% block title %}Galeria{% endblock %}</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
          </div>
        </div>

        <div class="row">
          {%for row in rows%}
          <div class="col-sm-4">
            <div class="box"><a href="{{row.image.url}}" title="" data-toggle="lightbox" data-gallery="portfolio" data-title="{{row.title}}" data-footer="{{row.desc}}"><img src="{{row.image_thumbnail.url}}" alt="" class="img-responsive"></a></div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Portfolio / gallery end-->
{% endblock %}