apps/core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .views import index, home, comocomprar, galeria, contato, eventos,detail_eventos,detail_colecoes,detail_galeria

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^home/$', home, name='home'),
	url(r'^galeria/$', galeria, name='all-galeria'),
	url(r'^contato/$', contato, name='contato'),
	url(r'^eventos/$', eventos, name='all-eventos'),
	url(r'^comocomprar/$', comocomprar, name='comocomprar'),
	url(r'^colecoes/(?P<slug>[\w-]+)/$', detail_colecoes, name='detail-colecoes'),
	url(r'^galeria/(?P<slug>[\w-]+)/$', detail_galeria, name='detail-galeria'),
	url(r'^eventos/(?P<slug>[\w-]+)/$', detail_eventos, name='detail-eventos'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

georginanogueira/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.core import urls as core_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(core_urls, namespace='core')),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
	<title>{% block title %}{% endblock %} | Georgina Nogueira</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="all,follow">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
	<link rel="stylesheet" href="{% static 'css/style.default.css' %}" />
	<link rel="stylesheet" href="{% static 'css/ekko-lightbox.css' %}" />
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon2.png' %}"/>
</head>
<body data-spy="scroll" data-target="#navigation" data-offset="120">
	{% include "nav.html" %}
	{% block content %}{% endblock %}
	{% include "foot.html" %}
	<!-- Javascript files-->
	<!-- jQuery-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-1.11.0.min.js' %}"><\/script>')</script>
<!-- Bootstrap CDN-->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!-- jQuery Cookie - For Demo Purpose-->
<script src="{% static 'js/jquery.cookie.js' %}"></script>
<script src="{% static 'js/ekko-lightbox.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'js/gmaps.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<!-- google maps-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
<!-- to use it on your site, generate your own API key for Google Maps and paste it above -->
<!-- main script-->
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID.-->
<script>
(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
	function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
e=o.createElement(i);r=o.getElementsByTagName(i)[0];
e.src='//www.google-analytics.com/analytics.js';
r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
ga('create','UA-XXXXX-X');ga('send','pageview');
</script>
</body>
</html>

templates/foot.html
<footer class="section-inverse">
  <div class="container"> 
    <div class="row copyright">
      <div class="col-md-6">
        <p>&copy;2017 Georgina Nogueira</p>
      </div>
      <div class="col-md-6">
        <p class="credit">Desenvolvido por <a href="#">NP Sistemas Web </a></p>
        <!-- Please do not remove the backlink to us unless you support the development at https://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :) -->
      </div>
    </div>
  </div>
</footer>

templates/nav.html
{% load static %}
<header class="header">
  <div class="sticky-wrapper">
    <div role="navigation" class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-btn btn-sm navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
              <a class="navbar-brand" href="{% url 'core:home'%}">
                  <span><img src="{% static 'images/logomarca/brand.png' %}"/></span>
                  Georgina Nogueira
              </a>
        </div>
        <div class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'core:home'%}">Início</a></li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Coleções<span class="caret"></span></a>
               <ul class="dropdown-menu">
                {% for menu in submenu %}
                 <li><a href="{% url 'core:detail-colecoes' slug=menu.slug %}">{{menu}}</a></li>
                {% endfor %}
               </ul>
             </li>
            <li><a href="{% url 'core:all-galeria'%}">Galeria</a></li>
            <li><a href="{% url 'core:all-eventos'%}">Eventos</a></li>
            <li><a href="{% url 'core:contato'%}">Contato</a></li>
            <li><a href="{% url 'core:comocomprar'%}">Como Comprar</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>